inference_node:
    ros__parameters:
        use_interrupt: true
        model_name: "policy_interrupt.onnx"
        act_alpha: 1.0
        gyro_alpha: 1.0
        angle_alpha: 1.0
        obs_num: 79
        frame_stack: 10
        joint_num: 23
        decimation: 4
        intra_threads: 1
        dt: 0.005
        obs_scales_lin_vel: 1.0
        obs_scales_ang_vel: 1.0
        obs_scales_dof_pos: 1.0
        obs_scales_dof_vel: 1.0
        obs_scales_gravity_b: 1.0
        clip_observations: 100.0
        action_scale: 0.25
        clip_actions: 100.0
        usd2urdf: [0, 6, 12, 1, 7, 13, 18, 2, 8, 14, 19, 3, 9, 15, 20, 4, 10, 16, 21, 5, 11, 17, 22]

