gmr_dof_names:
  - left_thigh_yaw_joint
  - left_thigh_roll_joint
  - left_thigh_pitch_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_thigh_yaw_joint
  - right_thigh_roll_joint
  - right_thigh_pitch_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  - torso_joint
  - left_arm_pitch_joint
  - left_arm_roll_joint
  - left_arm_yaw_joint
  - left_elbow_pitch_joint
  - left_elbow_yaw_joint
  - right_arm_pitch_joint
  - right_arm_roll_joint
  - right_arm_yaw_joint
  - right_elbow_pitch_joint
  - right_elbow_yaw_joint

lab_dof_names:
  - left_thigh_yaw_joint
  - right_thigh_yaw_joint
  - torso_joint
  - left_thigh_roll_joint
  - right_thigh_roll_joint
  - left_arm_pitch_joint
  - right_arm_pitch_joint
  - left_thigh_pitch_joint
  - right_thigh_pitch_joint
  - left_arm_roll_joint
  - right_arm_roll_joint
  - left_knee_joint
  - right_knee_joint
  - left_arm_yaw_joint
  - right_arm_yaw_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_elbow_pitch_joint
  - right_elbow_pitch_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
  - left_elbow_yaw_joint
  - right_elbow_yaw_joint

# Names of the key bodies that will be used in further processing
# Must match the names in the lab robot model
# Order matters and should align with that used in observation
lab_key_body_names:
  - left_ankle_roll_link
  - right_ankle_roll_link
  - left_elbow_yaw_link
  - right_elbow_yaw_link
  - left_arm_roll_link
  - right_arm_roll_link